version: '3.8'

services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki
    networks:
      - logging

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ./datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
      - grafana-storage:/var/lib/grafana
    networks:
      - logging

  log-importer:
    build:
      context: .
      dockerfile: Dockerfile.importer
      pull: true
    container_name: log-importer
    ports:
      - "8090:8080"
    networks:
      - logging
    environment:
      - LOKI_URL=http://loki:3100
      - PORT=8080

networks:
  logging:

volumes:
  loki-data:
  grafana-storage: